In [6]:
import numpy as np 

# Use dtype=object for arrays of lists with different lengths
arr = np.array([np.array([1,2,3,4,5]), np.array([11,12,13,14,15])], dtype=object)
print(arr)

add =np.add(arr[0],arr[1])


[[1 2 3 4 5]
 [11 12 13 14 15]]


In [9]:
arr=np.array([1,2,3,4,5,6])
print(arr[2:5])

[3 4 5]


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 'a'], dtype=object)

def safe_int(val):
	try:
		return int(val)
	except ValueError:
		return None

filtered = [safe_int(x) for x in arr if safe_int(x) is not None]
newarr = np.array(filtered, dtype=int)
print(newarr)
print(newarr.dtype)


[1 2 3 4 5 6 7]
int64


In [31]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1,0])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True  True  True False]
bool


In [32]:
arr=np.array([1,2,3,4,5,6])
x=arr.copy()
arr[1]=20
print(arr)
print(x)

[ 1 20  3  4  5  6]
[1 2 3 4 5 6]


In [34]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print((arr.shape))

(2, 4)
